scene:
  type: InteractiveTraversableScene
  # scene_model: Rs_int
  # scene_model: office_cubicles_left
  scene_model: Pomaria_1_int
  load_object_categories:
    - floors
    - walls
robots:
  - type: Tiago
    default_arm_pose: vertical
    position: [-11.0, 1.0, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
    # scale: 0.9
    # self_collisions: false
    # action_type: continuous
    # action_normalize: true
    controller_config:
      base:
        name: JointController
        motor_type: velocity
objects: []
